[[libroot_julia]]
arch = "x86_64"
git-tree-sha1 = "2f854aff2a356424448bab45474c262a4a0b330c"
libc = "glibc"
os = "linux"

    [[libroot_julia.download]]
    sha256 = "9d42cb59646a49b9f8190f5dcb294040807f41d84f75ed2d6882761a486e5d86"
    url = "https://github.com/grasph/libroot_julia_jll/releases/download/libroot_julia-v0.0.1+1/libroot_julia.v0.0.1.x86_64-linux-gnu.tar.gz"
[[libroot_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3b0106ba2a8b5996d98cbba13dc8f43637ef7864"
libc = "glibc"
os = "linux"

    [[libroot_julia.download]]
    sha256 = "c926529fffa74295960480d9431a745b2a4f795fdf3bec2c2618bcb9274fe0c8"
    url = "https://github.com/grasph/libroot_julia_jll/releases/download/libroot_julia-v0.0.1+4/libroot_julia.v0.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[libroot_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "567f41c7f6fc75fc61d496257adb86915f283eca"
libc = "glibc"
os = "linux"

    [[libroot_julia.download]]
    sha256 = "838b4c29a4c303555cc6f4eee226bf99d858cf6dc414a55e56da449ce6c0a975"
    url = "https://github.com/grasph/libroot_julia_jll/releases/download/libroot_julia-v0.0.1+4/libroot_julia.v0.0.1.x86_64-linux-gnu-cxx11.tar.gz"
