# Autogenerated wrapper script for libroot_julia_jll for x86_64-linux-gnu
export libroot_julia

using ROOT_jll
JLLWrappers.@generate_wrapper_header("libroot_julia")
JLLWrappers.@declare_library_product(libroot_julia, "libroot_julia.so")
function __init__()
    JLLWrappers.@generate_init_header(ROOT_jll)
    JLLWrappers.@init_library_product(
        libroot_julia,
        "lib/libroot_julia.so",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
